name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pnpm i
      - run: pnpm lint-check
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --pack-extension=src
      - run: test -f src.crx
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src.crx
