name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: pnpm i
      - run: pnpm lint-check
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --headless --pack-extension=src
      - run: cp src.crx newtab-override.crx
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: newtab-override.crx
