name: main
on: push
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      - run: npm ci
      - run: npm run prettier:check
      - run: apt-get install -y --no-install-recommends chromium-browser
      - run: npm run build:crx
      - run: cp src.crx newtab-override.crx
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: newtab-override.crx
